
services:
  - type: web
    name: cv-optimizer-pro
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:create_app() --config gunicorn.conf.py
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /
    disk:
      name: cv-optimizer-disk
      sizeGB: 1
      mountPath: /tmp
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: false
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: WEB_CONCURRENCY
        value: "2"
      - key: OPENROUTER_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ENCRYPTION_KEY
        sync: false

  - type: pserv
    name: cv-optimizer-db
    plan: free
    region: oregon
