
services:
  - type: web
    name: cv-optimizer-pro
    env: python
    plan: free
    # Build Command - install system dependencies first
    buildCommand: |
      apt-get update && apt-get install -y \
        build-essential \
        python3-dev \
        libxml2-dev \
        libxslt1-dev \
        zlib1g-dev \
        libjpeg-dev \
        libpng-dev \
        libfreetype6-dev \
        pkg-config \
        libffi-dev \
        libssl-dev \
        libmagic-dev \
        poppler-utils \
        tesseract-ocr \
        tesseract-ocr-pol \
        tesseract-ocr-eng && \
      pip install --upgrade pip setuptools wheel && \
      pip install -r requirements.txt
    # Start Command
    startCommand: "gunicorn --config gunicorn.conf.py app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: false
      - key: PORT
        value: 10000
      - key: UPLOAD_FOLDER
        value: /tmp/uploads
      - key: MAX_CONTENT_LENGTH
        value: 16777216
