
services:
  - type: web
    name: cv-optimizer-pro
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: false
      - key: PORT
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
